### ISSUE TITLE
Error when Evaluation

### ISSUE THREAD

**Issue by MarioUncle-Wang** [NVlabs/FB-BEV#34]
Hello,
  I have completed the model training phase , but an error occurred during the evaluation. The specific information is as follows：
![1714092298627](https://github.com/NVlabs/FB-BEV/assets/81735762/3742080e-e9c3-4aea-8822-ad3412cfe97c)

**Comment by heng-yuwen** [comment]
same here

**Comment by heng-yuwen** [comment]
Upgrade your mmcv-full to 1.5.3

**Comment by MarioUncle-Wang** [comment]
> Upgrade your mmcv-full to 1.5.3

i have already upgarde my mmcv-full to 1.5.3 but it doesnt work. my pip lists are as follows:
![屏幕截图 2024-05-07 10:02:02](https://github.com/NVlabs/FB-BEV/assets/81735762/c962aee7-030f-4a60-a3e7-0cf4b89f00b9)
![屏幕截图 2024-05-07 10:02:19](https://github.com/NVlabs/FB-BEV/assets/81735762/b810594a-ced0-4b48-a1ba-6e3a2808f96e)

**Comment by heng-yuwen** [comment]
> > Upgrade your mmcv-full to 1.5.3
> 
> i have already upgarde my mmcv-full to 1.5.3 but it doesnt work. my pip lists are as follows: ![屏幕截图 2024-05-07 10:02:02](https://private-user-images.githubusercontent.com/81735762/328363613-c962aee7-030f-4a60-a3e7-0cf4b89f00b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDg0MTIsIm5iZiI6MTcxNTA0ODExMiwicGF0aCI6Ii84MTczNTc2Mi8zMjgzNjM2MTMtYzk2MmFlZTctMDMwZi00YTYwLWEzZTctMGNmNGI4OWYwMGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAyMTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMGY3N2M4ZTE1OTAyZDM3NjZhZjUxZGI1NTA3OWQ2MjBmYWMzYzEzNjczODI2YWI3NTkwNWQ5YThkNGRjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4LuPPK_aZgEuCu4nSfS-zdBBx5-L6QEplwc0LrLGdY) ![屏幕截图 2024-05-07 10:02:19](https://private-user-images.githubusercontent.com/81735762/328363634-b810594a-ced0-4b48-a1ba-6e3a2808f96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDg0MTIsIm5iZiI6MTcxNTA0ODExMiwicGF0aCI6Ii84MTczNTc2Mi8zMjgzNjM2MzQtYjgxMDU5NGEtY2VkMC00YjQ4LWExYmEtNmUzYTI4MDhmOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAyMTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzN2FmNDhmY2NhNjFmZTA1Njc1M2E3MjExZWZkMDEwM2QxZWJkYjUyNTEwNDg4MjhlNzVjZTBjZDc1ZjUyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YgTL5wcN1NgaM6nRmoOqSqzN3eYduTiTm9T2C2DXf7s)

``
FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

# install python3.8 and env packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install wget -yq \
    && apt-get install build-essential g++ gcc -y \
    && apt-get install libgl1-mesa-glx libglib2.0-0 -y \
    && apt-get install openmpi-bin openmpi-common libopenmpi-dev libgtk2.0-dev git -y \
    && apt-get install python3.8-dev tmux zip unzip -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN rm /usr/bin/python3 && ln -s /usr/bin/python3.8 /usr/bin/python3

RUN wget https://bootstrap.pypa.io/get-pip.py && python ./get-pip.py && rm get-pip.py
RUN pip install --upgrade pip

RUN pip install --no-cache-dir pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install --no-cache-dir mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.0/index.html
RUN pip install --no-cache-dir mmdet==2.24.0 mmsegmentation==0.24.0 timm nuscenes-devkit==1.1.6

# install FB-BEV
WORKDIR /root
RUN git clone https://github.com/NVlabs/FB-BEV.git
WORKDIR /root/FB-BEV
ENV PYTHONPATH=${PYTHONPATH}:/root/FB-BEV

RUN pip install --no-cache-dir -e .
RUN pip install --no-cache-dir numpy==1.20.3 spconv-cu113

# config git
RUN git config --global user.name "Yuwen Heng"
RUN git config --global user.email "hengyuwen@outlook.com"

# download ckpts
RUN mkdir ckpts && cd ckpts && \
    wget https://github.com/zhiqi-li/storage/releases/download/v1.0/fbocc-r50-cbgs_depth_16f_16x4_20e.pth
``

**Comment by heng-yuwen** [comment]
@MarioUncle-Wang try mmcv-full==1.6.0.

**Comment by MarioUncle-Wang** [comment]
> @MarioUncle-Wang try mmcv-full==1.6.0.

it worked! Thanks for your support.
