### ISSUE TITLE
whether FB-BEV uses BEV backbone?

### ISSUE THREAD

**Issue by SPA-junghokim** [NVlabs/FB-BEV#6]
I would like to express my gratitude for your excellent research. I had always been curious about whether using both forward and backward projections for BEV representation would enhance its performance. I had contemplated taking this up as a research topic. I was particularly astounded by the improvement in performance when a module for depth was added during the backward projection.

One aspect I'm curious about is the experiment with ResNet-50 mentioned in your paper. From what I observed, the FLOPS are lower compared to when BEVDepth is reproduced. I anticipate that to achieve this, one cannot use the BEVBackbone + neck portion utilized in BEVDepth. Could you confirm if my assumption is correct?

Thank you.

**Comment by zhiqi-li** [comment]
We have lower FLOPs compared to BEVDepth due to we use smaller feature dimension. We still use BEV-Backbone, which is an important module for final performance.

**Comment by SPA-junghokim** [comment]
Thank you for your response! It cleared up a lot of my questions. Once again, I appreciate your research. I hope we can meet at a reputable conference in the future!
